'use client'

// import type { ReactElement } from 'react'
// // import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
import { Box, Typography } from '@mui/material'

// import { useThemeModes } from '@/hooks/useThemeModes'
// import { ThemeProvider } from '@mui/material/styles'

// import CssBaseline from '@mui/material/CssBaseline'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export const AppProviders = ({ children }: { children: ReactNode | ReactNode[] }) => {
//   const theme = useThemeModes()

//   return <ThemeProvider theme={theme}>{children}</ThemeProvider>
// }

const ExampleComponent = () => {
  //   return (
  //     <html lang="en">
  //       <body className={inter.className}>
  //         {/* <AppProviders> */}
  //         {/* <CssBaseline /> */}
  //         {children}
  //         {/* </AppProviders> */}
  //       </body>
  //     </html>
  //   )

  return (
    <Box>
      <Typography>Example</Typography>
    </Box>
  )
}

export default ExampleComponent
