// TVChartContainer.tsx
import { useEffect, useRef } from 'react'

import { CustomUDFDatafeed } from '@/lib/CustomDatafeed'
import { widget } from '@/public/charting_library'
import type {
  ChartingLibraryWidgetOptions,
  LanguageCode,
  ResolutionString,
  TimeFrameValue,
} from '@/public/charting_library'
import { useStrategyStore } from '@/store/useStrategyStore'
import { proTheme } from '@/styles/colors'

import Card from '../common/Card'

export const TVChartContainer = () => {
  const chartContainerRef = useRef<HTMLDivElement>() as React.MutableRefObject<HTMLInputElement>
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tvWidgetRef = useRef<any>(null)
  const { coin } = useStrategyStore()

  const defaultWidgetProps: Partial<ChartingLibraryWidgetOptions> = {
    symbol: `mo${coin}`, // Default token
    interval: 'D' as ResolutionString,
    library_path: '/charting_library/',
    locale: 'en',
    charts_storage_url: 'https://saveload.tradingview.com',
    charts_storage_api_version: '1.1',
    client_id: 'tradingview.com',
    user_id: 'public_user_id',
    fullscreen: false,
    autosize: true,
  }

  useEffect(() => {
    const widgetOptions: ChartingLibraryWidgetOptions = {
      symbol: defaultWidgetProps.symbol,
      datafeed: new CustomUDFDatafeed(),
      interval: '1D' as ResolutionString,
      container: chartContainerRef.current,
      library_path: defaultWidgetProps.library_path,
      locale: defaultWidgetProps.locale as LanguageCode,
      disabled_features: [
        'use_localstorage_for_settings',
        'header_resolutions', // Remove header resolution options
        'left_toolbar', // Remove the left toolbar (draw tools)
        'header_chart_type',
        'create_volume_indicator_by_default',
      ],
      enabled_features: [],
      charts_storage_url: defaultWidgetProps.charts_storage_url,
      charts_storage_api_version: defaultWidgetProps.charts_storage_api_version,
      client_id: defaultWidgetProps.client_id,
      user_id: defaultWidgetProps.user_id,
      fullscreen: defaultWidgetProps.fullscreen,
      autosize: defaultWidgetProps.autosize,
      toolbar_bg: '#ff0000',
      overrides: {
        'mainSeriesProperties.style': 2, // 2 represents the line chart style
        'mainSeriesProperties.priceLineColor': proTheme.primary,
        'mainSeriesProperties.lineStyle.color': proTheme.primary,
        'paneProperties.background': proTheme.dark,
        'mainSeriesProperties.areaStyle.color1': proTheme.primary,
        'paneProperties.vertGridProperties.color': 'rgba(255,255,255, .1)',
        'paneProperties.horzGridProperties.color': 'rgba(255,255,255, .1)',
        'scalesProperties.textColor': proTheme.offWhite,
        'paneProperties.legendProperties.showBackground': 'false',
      },
    }

    const tvWidget = new widget({
      custom_themes: {
        light: {
          color1: [
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
            proTheme.primary,
          ],
          // Color that overrides grey
          color2: [
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
          ],
          // Color that overrides red
          color3: [
            '#fff0f0',
            '#ffe1e1',
            '#ffd3d3',
            '#ffc4c4',
            '#ffb5b5',
            '#ffa6a6',
            '#ff9797',
            '#ff8888',
            '#ff7a7a',
            '#ff6b6b',
            '#ff4d4d',
            '#ea4747',
            '#d54040',
            '#bf3a3a',
            '#aa3333',
            '#952d2d',
            '#802727',
            '#6a2020',
            '#551a1a',
          ],
          // Color that overrides green
          color4: [
            '#f2fdf8',
            '#e5faf0',
            '#d7f8e9',
            '#caf5e1',
            '#bdf3da',
            '#b0f1d2',
            '#a2eecb',
            '#95ecc3',
            '#88e9bc',
            '#7be7b4',
            '#60e2a5',
            '#58cf97',
            '#50bc8a',
            '#48aa7c',
            '#40976e',
            '#388460',
            '#307153',
            '#285e45',
            '#204b37',
          ],
          // Color that overrides orange
          color5: [
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
            proTheme.offWhite,
          ],
          // Color that overrides purple
          color6: [
            '#feeafe',
            '#fcd5fc',
            '#fbbffb',
            '#f9aaf9',
            '#f895f8',
            '#f780f7',
            '#f56af5',
            '#f455f4',
            '#f240f2',
            '#f12bf1',
            '#ee00ee',
            '#da00da',
            '#c600c6',
            '#b300b3',
            '#9f009f',
            '#8b008b',
            '#770077',
            '#630063',
            '#4f004f',
          ],
          // Color that overrides yellow
          color7: [
            '#fefeea',
            '#fcfcd5',
            '#fbfbbf',
            '#f9f9aa',
            '#f8f895',
            '#f7f780',
            '#f5f56a',
            '#f4f455',
            '#f2f240',
            '#f1f12b',
            '#eeee00',
            '#dada00',
            '#c6c600',
            '#b3b300',
            '#9f9f00',
            '#8b8b00',
            '#777700',
            '#636300',
            '#4f4f00',
          ],
          white: proTheme.dark,
          black: proTheme.offWhite,
        },
        dark: {
          color1: [
            '#fbefea',
            '#f7dfd5',
            '#f3cfc0',
            '#efbfaa',
            '#ebaf95',
            '#e89f80',
            '#e48f6b',
            '#e07f56',
            '#dc6f41',
            '#d85f2b',
            '#d03f01',
            '#bf3a01',
            '#ad3501',
            '#9c2f01',
            '#8b2a01',
            '#792501',
            '#682001',
            '#571a00',
            '#451500',
          ],
          color2: [
            '#f8eeee',
            '#f1dede',
            '#eacdcd',
            '#e2bcbc',
            '#dbacac',
            '#d49b9b',
            '#cd8a8a',
            '#c67a7a',
            '#bf6969',
            '#b75858',
            '#a93737',
            '#9b3232',
            '#8d2e2e',
            '#7f2929',
            '#712525',
            '#632020',
            '#551c1c',
            '#461717',
            '#381212',
          ],
          color3: [
            '#fff0f0',
            '#ffe1e1',
            '#ffd3d3',
            '#ffc4c4',
            '#ffb5b5',
            '#ffa6a6',
            '#ff9797',
            '#ff8888',
            '#ff7a7a',
            '#ff6b6b',
            '#ff4d4d',
            '#ea4747',
            '#d54040',
            '#bf3a3a',
            '#aa3333',
            '#952d2d',
            '#802727',
            '#6a2020',
            '#551a1a',
          ],
          color4: [
            '#f2fffb',
            '#e6fff7',
            '#d9fff2',
            '#ccffee',
            '#bfffea',
            '#b3ffe6',
            '#a6ffe1',
            '#99ffdd',
            '#8cffd9',
            '#80ffd5',
            '#66ffcc',
            '#5eeabb',
            '#55d5aa',
            '#4dbf99',
            '#44aa88',
            '#3c9577',
            '#338066',
            '#2b6a55',
            '#225544',
          ],
          color5: [
            '#fffff0',
            '#ffffe0',
            '#feffd1',
            '#feffc2',
            '#feffb2',
            '#feffa3',
            '#fdff94',
            '#fdff84',
            '#fdff75',
            '#fdff66',
            '#fcff47',
            '#e7ea41',
            '#d2d53b',
            '#bdbf35',
            '#a8aa2f',
            '#939529',
            '#7e8024',
            '#696a1e',
            '#545518',
          ],
          color6: [
            '#fff1ff',
            '#ffe2ff',
            '#ffd4ff',
            '#ffc5ff',
            '#ffb7ff',
            '#ffa9ff',
            '#ff9aff',
            '#ff8cff',
            '#ff7dff',
            '#ff6fff',
            '#ff52ff',
            '#ea4bea',
            '#d544d5',
            '#bf3ebf',
            '#aa37aa',
            '#953095',
            '#802980',
            '#6a226a',
            '#551b55',
          ],
          color7: [
            '#eff8ff',
            '#dff1ff',
            '#cfeaff',
            '#bee3ff',
            '#aedcff',
            '#9ed5ff',
            '#8eceff',
            '#7ec7ff',
            '#6ec0ff',
            '#5db9ff',
            '#3dabff',
            '#389dea',
            '#338fd5',
            '#2e80bf',
            '#2972aa',
            '#246495',
            '#1f5680',
            '#19476a',
            '#143955',
          ],
          white: proTheme.dark,
          black: proTheme.offWhite,
        },
      },
      ...widgetOptions,
    })

    tvWidgetRef.current = tvWidget

    tvWidget.onChartReady(() => {
      tvWidget.chart().createStudy(
        'Overlay',
        true,
        true,
        { symbol: coin },
        {
          style: 2,
          'lineStyle.color': proTheme.offWhite,
        },
        { priceScale: 'as-series' },
      )
      tvWidget.chart().setTimeFrame({
        val: { type: 'period-back', value: '56M' } as TimeFrameValue,
        res: '1D' as ResolutionString,
      })
      tvWidget.setCSSCustomProperty('--tv-color-toolbar-button-background-hover', proTheme.payne)
      tvWidget.setCSSCustomProperty('--tv-color-popup-element-background-hover', proTheme.payne)
      tvWidget.setCSSCustomProperty('--tv-color-toolbar-button-text-active-hover', proTheme.primary)
    })

    return () => {
      tvWidget.remove()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [coin])

  return (
    <Card className="h-full min-h-[70vh] w-full !p-0">
      <div ref={chartContainerRef} className="h-full w-full p-5" />
    </Card>
  )
}
