export const WALLET_CONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID

export const OWNER_PK = process.env.NEXT_PUBLIC_PRIVATE_KEY

export const LIVE_PRICES = process.env.NEXT_LIVE_PRICES
