export const WALLET_CONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID

export const PRIVATE_KEY = process.env.NEXT_PRIVATE_KEY

export const STAGING_PASSWORD = process.env.NEXT_STAGING_PASSWORD
